name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nodeJs
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18"

      - name: Install Deps
        run: npm i

      - name: Build app bundle
        run: npm run build:prod

      - name: Deploy to pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          build_dir: dist/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
